1:
  name: Ethereum
  wss: "wss://ethereum.publicnode.com"
  https:
    - "https://ethereum.publicnode.com"
    - "https://rpc.ankr.com/eth"
56:
  name: BNB
  wss: "wss://bsc.publicnode.com"
  https:
    - "https://rpc.ankr.com/bsc"
204:
  name: opBNB
  wss: "wss://opbnb.publicnode.com"
  https:
    - "https://opbnb.publicnode.com"
    - "https://1rpc.io/opbnb"
97:
  name: BNB
  wss: "wss://bsc-testnet.publicnode.com"
  https:
    - "https://bsc-testnet.publicnode.com"
    - "https://data-seed-prebsc-1-s2.bnbchain.org:8545"
    - "https://data-seed-prebsc-2-s2.bnbchain.org:8545"
