version: "3.9"
networks:
  insc-indexer-net:
    driver: bridge
services:
  insc-indexer-97:
    restart: always
    working_dir: /app/insc-indexer-97
    environment:
      - CHAIN_ID=${97}
    image: insc-indexer-97:v1
    command: ./insc-indexer-97
    networks:
      - insc-indexer-net
