version: "3.9"
networks:
  inscription-net:
    driver: bridge
services:
  inscription:
    restart: always
    working_dir: /app/inscription-${CHAIN}
    environment:
      - CHAIN=${CHAIN}
      - RPC_URL=${RPC_URL}
    image: inscription-${CHAIN}:v1
    command: ./inscription-${CHAIN}
    networks:
      - inscription-net
